name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-on-ubuntu-net6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        run: dotnet test LikeComparison.Tests --framework net6.0 --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov
      - name: Run coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./LikeComparison.Tests/coverage.net6.0.info
        if: github.event_name != 'pull_request'
  test-on-ubuntu-net7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Run unit tests
        run: dotnet test LikeComparison.Tests --framework net7.0 --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov