name: Build, Test, coveralls.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [LikeComparison, LikeComparison.MSTest, LikeComparison.Shouldly]
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet build ${{ matrix.package }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [net6.0, net7.0, net8.0]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Run unit tests
        run: dotnet test LikeComparison.Tests --framework ${{ matrix.framework }} --configuration Release -e CollectCoverage=true -e CoverletOutputFormat=lcov
      - name: Run coveralls.io
        if: ${{ matrix.framework == 'net6.0' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./LikeComparison.Tests/coverage.net6.0.info