name: Unit tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Run unit tests
        run: dotnet test LikeComparison.Tests --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=lcov